name: CI

on:
  pull_request:
  push:
    branches:
      - develop
    tags:
      - 'v*'

jobs:
  build:
    name: Build postcli
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os:
        - windows-latest
    steps:
      - name: Add OpenCL support - Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get update -q && sudo apt-get install -qy ocl-icd-opencl-dev libpocl2
      - name: disable Windows Defender - Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          Set-MpPreference -DisableRealtimeMonitoring $true
      - name: checkout
        uses: actions/checkout@v4
      - name: set up go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: "go.mod"
      - name: setup env
        run: make install
      - name: build postcli
        run: make build
      - name: Prepare release archive
        shell: bash
        run: |
          rm -f ./build/post.h
          cp ./cmd/postcli/README.md ./build/
      - name: Set name of release archive
        shell: bash
        run: |
          if [[ ${{ runner.arch }} == "ARM64" ]]; then
            echo "OUTNAME=${{ runner.os }}_${{ runner.arch }}" >> $GITHUB_ENV
          else
            echo "OUTNAME=${{ runner.os }}" >> $GITHUB_ENV
          fi
      - name: Archive postcli artifacts
        uses: actions/upload-artifact@v4
        with:
          name: postcli-${{ env.OUTNAME }}.zip
          path: ./build/*
          if-no-files-found: error

  release:
    name: Publish release
    if: github.event_name == 'push' && github.ref_type == 'tag'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/assets
      - name: Create archives
        run: |
          mkdir ./artifacts;
          for dir in ./assets/*/; do
            7z a -tzip "${{ github.workspace }}/artifacts/$(basename $dir)" "$dir/*";
          done
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/artifacts/*.zip
          prerelease: false
          draft: true
          fail_on_unmatched_files: true
